/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-03-31 07:08:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.doctorjsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/doctorjsp/inc/header.jsp", Long.valueOf(1459241692000L));
    _jspx_dependants.put("/WEB-INF/doctorjsp/inc/common.jsp", Long.valueOf(1458622510000L));
    _jspx_dependants.put("/WEB-INF/doctorjsp/inc/footer.jsp", Long.valueOf(1459307776000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\r');
      out.write('\n');
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>OMAS (Online Medical Appointment System)</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/template.css\" />\r\n");
      out.write("<script src=\"js1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js1/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js1/my.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"myheader\">\r\n");
      out.write("\t\t\t\t <img src=\"images/aoa_header.jpg\" class=\"img-responsive\" />\t\t\t \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"Doctoromas.do\">OMAS</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a href=\"#\">Hospital</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"docfaq.do\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"docContactMailPathFist.do\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"doctorloginPathFirst.do\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> Login </a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"panel panel-success\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">Sakura Hospital</div>\r\n");
      out.write("\t\t<div class=\"panel-body col-sm-8\">\r\n");
      out.write("\t\t\t<p>No.23,Shin Saw Pu Road,Sanchaung Township,Yangon,Myanmar</p>\r\n");
      out.write("\t\t\t<p>01512668 / 01512669,01510079,01613886,01513887 .</p>\r\n");
      out.write("\t\t\t<p>EDP@sakurahospital.com.mm</p>\r\n");
      out.write("\t\t\t<p>http:.//www.sakurahospital.com.mm</p>\r\n");
      out.write("\t\t\t<p>01512668</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"panel-body col-sm-4\">\r\n");
      out.write("\t\t\t<img src=\"myimage/sakura.jpg\" class=\"img-responsive img-rounded\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%\" alt=\"Image\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">SSC Hospital</div>\r\n");
      out.write("\t\t<div class=\"panel-body col-sm-4\">\r\n");
      out.write("\t\t\t<img src=\"myimage/ssc.jpg\" class=\"img-responsive img-rounded\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%\" alt=\"Image\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"panel-body col-sm-8\">\r\n");
      out.write("\t\t\t<p>SSC Hospial</p>\r\n");
      out.write("\t\t\t<p>Shwegondaing Rd, Yangon 11201, Myanmar (Burma),</p>\r\n");
      out.write("\t\t\t<p> Tamwe Township , Yangon.</p>\r\n");
      out.write("\t\t\t<p>01545851 / 01-545759 / +95 9 794 507456</p>\r\n");
      out.write("\t\t\t<p>01545851</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"panel panel-success\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">Shwe Baho Hospital</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"panel-body col-sm-8\">\r\n");
      out.write("\t\t\t\t<p>Shwe Ba Ho</p>\r\n");
      out.write("\t\t\t\t<p>No.1/33 , Thema Byanar Road , Kyukkasan Road & Corner of\r\n");
      out.write("\t\t\t\t\tThemabyanar Road , Matharyaemon</p>\r\n");
      out.write("\t\t\t\t<p>, Tamwe Township , Yangon.</p>\r\n");
      out.write("\t\t\t\t<p>01545851 / 01-545759 / 01-548605 / 01-548367 / 01-544090 /\r\n");
      out.write("\t\t\t\t\t01-548783</p>\r\n");
      out.write("\t\t\t\t<p>01545851</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"panel-body col-sm-4\">\r\n");
      out.write("\t\t\t\t<img src=\"myimage/shwebaho.jpg\" class=\"img-responsive img-rounded\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%\" alt=\"Image\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<footer class=\"container-fluid text-center\">\n");
      out.write("  www.omasictti.com © 2016 Online Medical Appointment | Site Privacy policy | Featured snippets are OMAS license.\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
