/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-02-15 09:41:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_005fhome_005f001_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/jsp/inc/common.jsp", Long.valueOf(1455093953000L));
    _jspx_dependants.put("/WEB-INF/jsp/inc/footer.jsp", Long.valueOf(1454993083000L));
    _jspx_dependants.put("/WEB-INF/jsp/inc/left_menu.jsp", Long.valueOf(1455514616000L));
    _jspx_dependants.put("/WEB-INF/jsp/inc/logout.jsp", Long.valueOf(1454993083000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Framework Home Page</title>\n");
      out.write("<link href=\"css/library.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h3 align=\"center\">Framework Home Page</h3>\n");
      out.write("<hr>\n");
      out.write("<table border=\"1\" width=\"100%\">\n");
      out.write("\t");
      out.write("<tr>\n");
      out.write("     <td align=\"left\"><font color=\"green\">Welcome\n");
      out.write("     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentFormBean.loginStudent.studentName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font></td>\n");
      out.write("      <td align=\"right\"><a href=\"logoutPath.do\">Logout</a></td>\n");
      out.write("</tr>");
      out.write("\n");
      out.write("\t<tr>\n");
      out.write("\t\t");
      out.write("<td align=\"left\" width=\"250\">\n");
      out.write("<table>\n");
      out.write("   <tr><td><a href=\"updatePathFirst.do\">Update Profile</a></td></tr>\n");
      out.write("   <tr><td><a href=\"calendarPathFirst.do\">Create Calendar</a></td></tr>\n");
      out.write("   <tr><td><a href=\"mailPathFirst.do\">Send Email to One</a></td></tr>\n");
      out.write("   <tr><td><a href=\"manyMailPathFirst.do\">Send Email to Many</a></td></tr>\n");
      out.write("   <tr><td><a href=\"autoComplementPath.do\">AutoComplement</a></td></tr>\n");
      out.write("   <tr><td><a href=\"pagingPath.do?frmControl=1\">Next/Previous Button Control</a></td>\n");
      out.write("   </tr>\n");
      out.write("   <tr><td><a href=\"searchPath.do?frmControl=1\">Book Search by Criteria</a></td>\n");
      out.write("   </tr>\n");
      out.write("   <tr><td><a href=\"catSubPath.do?frmControl=1\">Category/Subcategory</a></td></tr>\n");
      out.write("   <tr><td><a href=\"displayPath.do?frmControl=1\">Display Tag</a></td></tr>\n");
      out.write("   <tr><td><a href=\"filePath.do\">File Upload/Download</a></td></tr>\n");
      out.write("   <tr><td><a href=\"excelPath.do\">Create and Download Excel File</a></td></tr>\n");
      out.write("   <tr><td><a href=\"jfreeChartPath.do\">JFree Chart</a></td></tr>\n");
      out.write("<tr><td><a href=\"checkLdapPath.do\">Check ICTTI Student at LADP Server</a></td></tr>\n");
      out.write("<tr><td><a href=\"amazonPath.do\">Book Search by Amazon</a></td></tr>\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("\n");
      out.write("\t\t<td>\n");
      out.write("\t\t<h3 align=\"center\">ICTTI Frame Work Lectures</h3>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("<!-- footer -->\n");
      out.write("<hr>\n");
      out.write("<div>\n");
      out.write("<table width=\"100%\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td align=\"left\">&copy; Copyright 2011</td>\n");
      out.write("\t\t<td align=\"right\">Created by ICTTI</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("<!-- end footer -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
